name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          cd /packages/client
          npm run-script build
        env:
          REACT_APP_SERVER_URI: ${{ secrets.REACT_APP_APIKey }}
          REACT_APP_WEATHER_API_ID: ${{ secrets.REACT_APP_APISecret }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
